// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mouselive.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountType int32

const (
	AccountType_all       AccountType = 0
	AccountType_venue     AccountType = 1
	AccountType_fan       AccountType = 2
	AccountType_artist    AccountType = 3
	AccountType_organizer AccountType = 4
)

var AccountType_name = map[int32]string{
	0: "all",
	1: "venue",
	2: "fan",
	3: "artist",
	4: "organizer",
}

var AccountType_value = map[string]int32{
	"all":       0,
	"venue":     1,
	"fan":       2,
	"artist":    3,
	"organizer": 4,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d2ba8147a9cd784f, []int{0}
}

// The request message containing the user's name.
type NewAccountsRequest struct {
	Size                 int64       `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Number               int64       `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Period               int64       `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	Type                 AccountType `protobuf:"varint,4,opt,name=type,proto3,enum=protobuf.AccountType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NewAccountsRequest) Reset()         { *m = NewAccountsRequest{} }
func (m *NewAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*NewAccountsRequest) ProtoMessage()    {}
func (*NewAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2ba8147a9cd784f, []int{0}
}

func (m *NewAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountsRequest.Unmarshal(m, b)
}
func (m *NewAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountsRequest.Marshal(b, m, deterministic)
}
func (m *NewAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountsRequest.Merge(m, src)
}
func (m *NewAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_NewAccountsRequest.Size(m)
}
func (m *NewAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountsRequest proto.InternalMessageInfo

func (m *NewAccountsRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *NewAccountsRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *NewAccountsRequest) GetPeriod() int64 {
	if m != nil {
		return m.Period
	}
	return 0
}

func (m *NewAccountsRequest) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_all
}

// The response message containing the greetings
type AccountsResponse struct {
	Account              []*AccountStruct `protobuf:"bytes,1,rep,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AccountsResponse) Reset()         { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()    {}
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2ba8147a9cd784f, []int{1}
}

func (m *AccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsResponse.Unmarshal(m, b)
}
func (m *AccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsResponse.Marshal(b, m, deterministic)
}
func (m *AccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsResponse.Merge(m, src)
}
func (m *AccountsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsResponse.Size(m)
}
func (m *AccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsResponse proto.InternalMessageInfo

func (m *AccountsResponse) GetAccount() []*AccountStruct {
	if m != nil {
		return m.Account
	}
	return nil
}

type AccountStruct struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            int64       `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Address              string      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AccountType          AccountType `protobuf:"varint,4,opt,name=accountType,proto3,enum=protobuf.AccountType" json:"accountType,omitempty"`
	Status               string      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ImageLink            string      `protobuf:"bytes,6,opt,name=imageLink,proto3" json:"imageLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountStruct) Reset()         { *m = AccountStruct{} }
func (m *AccountStruct) String() string { return proto.CompactTextString(m) }
func (*AccountStruct) ProtoMessage()    {}
func (*AccountStruct) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2ba8147a9cd784f, []int{2}
}

func (m *AccountStruct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStruct.Unmarshal(m, b)
}
func (m *AccountStruct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStruct.Marshal(b, m, deterministic)
}
func (m *AccountStruct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStruct.Merge(m, src)
}
func (m *AccountStruct) XXX_Size() int {
	return xxx_messageInfo_AccountStruct.Size(m)
}
func (m *AccountStruct) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStruct.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStruct proto.InternalMessageInfo

func (m *AccountStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountStruct) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccountStruct) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AccountStruct) GetAccountType() AccountType {
	if m != nil {
		return m.AccountType
	}
	return AccountType_all
}

func (m *AccountStruct) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AccountStruct) GetImageLink() string {
	if m != nil {
		return m.ImageLink
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf.AccountType", AccountType_name, AccountType_value)
	proto.RegisterType((*NewAccountsRequest)(nil), "protobuf.NewAccountsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "protobuf.AccountsResponse")
	proto.RegisterType((*AccountStruct)(nil), "protobuf.AccountStruct")
}

func init() { proto.RegisterFile("mouselive.proto", fileDescriptor_d2ba8147a9cd784f) }

var fileDescriptor_d2ba8147a9cd784f = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0xcb, 0xda, 0x40,
	0x10, 0xc6, 0xdf, 0x98, 0x98, 0x34, 0x23, 0xda, 0x30, 0xd0, 0x76, 0x11, 0x0f, 0x92, 0x93, 0xed,
	0x41, 0xa8, 0x3d, 0xf4, 0x2c, 0x45, 0xbc, 0x48, 0x29, 0x69, 0xa1, 0xe7, 0x35, 0x19, 0x65, 0xa9,
	0xd9, 0xa4, 0xfb, 0xc7, 0xa2, 0xd7, 0x7e, 0xbb, 0x7e, 0xaa, 0x92, 0x4d, 0x6c, 0x2c, 0xc2, 0x7b,
	0xca, 0x3e, 0xbf, 0x19, 0x66, 0x9f, 0x27, 0xb3, 0xf0, 0xb2, 0xac, 0xac, 0xa6, 0x93, 0x38, 0xd3,
	0xb2, 0x56, 0x95, 0xa9, 0xf0, 0x85, 0xfb, 0xec, 0xed, 0x21, 0xfd, 0xed, 0x01, 0x7e, 0xa6, 0x5f,
	0xeb, 0x3c, 0xaf, 0xac, 0x34, 0x3a, 0xa3, 0x9f, 0x96, 0xb4, 0x41, 0x84, 0x40, 0x8b, 0x2b, 0x31,
	0x6f, 0xee, 0x2d, 0xfc, 0xcc, 0x9d, 0xf1, 0x35, 0x84, 0xd2, 0x96, 0x7b, 0x52, 0x6c, 0xe0, 0x68,
	0xa7, 0x1a, 0x5e, 0x93, 0x12, 0x55, 0xc1, 0xfc, 0x96, 0xb7, 0x0a, 0xdf, 0x42, 0x60, 0x2e, 0x35,
	0xb1, 0x60, 0xee, 0x2d, 0x26, 0xab, 0x57, 0xcb, 0xdb, 0x9d, 0xcb, 0xee, 0xb2, 0x6f, 0x97, 0x9a,
	0x32, 0xd7, 0x92, 0x6e, 0x20, 0xe9, 0x1d, 0xe8, 0xba, 0x92, 0x9a, 0xf0, 0x3d, 0x44, 0xbc, 0x65,
	0xcc, 0x9b, 0xfb, 0x8b, 0xd1, 0xea, 0xcd, 0xc3, 0x84, 0xaf, 0x46, 0xd9, 0xdc, 0x64, 0xb7, 0xbe,
	0xf4, 0x8f, 0x07, 0xe3, 0xff, 0x4a, 0x4d, 0x0e, 0xc9, 0xcb, 0x36, 0x47, 0x9c, 0xb9, 0x33, 0xce,
	0x20, 0xce, 0x15, 0x71, 0x43, 0xc5, 0xda, 0x74, 0x51, 0x7a, 0x80, 0x0c, 0x22, 0x5e, 0x14, 0x8a,
	0xb4, 0x76, 0x71, 0xe2, 0xec, 0x26, 0xf1, 0x23, 0x8c, 0x78, 0xef, 0xfc, 0xf9, 0x58, 0xf7, 0x9d,
	0xcd, 0x0f, 0xd2, 0x86, 0x1b, 0xab, 0xd9, 0xd0, 0x4d, 0xec, 0x54, 0x63, 0x44, 0x94, 0xfc, 0x48,
	0x3b, 0x21, 0x7f, 0xb0, 0xd0, 0x95, 0x7a, 0xf0, 0x6e, 0x03, 0xa3, 0xbb, 0x89, 0x18, 0x81, 0xcf,
	0x4f, 0xa7, 0xe4, 0x09, 0x63, 0x18, 0x9e, 0x49, 0x5a, 0x4a, 0xbc, 0x86, 0x1d, 0xb8, 0x4c, 0x06,
	0x08, 0x10, 0x72, 0x65, 0x84, 0x36, 0x89, 0x8f, 0x63, 0x88, 0x2b, 0x75, 0xe4, 0x52, 0x5c, 0x49,
	0x25, 0xc1, 0xea, 0x3b, 0x44, 0xdb, 0xec, 0xcb, 0xa7, 0x75, 0x2d, 0x70, 0x07, 0x93, 0x2d, 0x99,
	0xbb, 0x6d, 0xe3, 0xac, 0x77, 0xff, 0xf8, 0x08, 0xa6, 0xd3, 0x87, 0x6c, 0xff, 0xb6, 0x93, 0x3e,
	0xed, 0x43, 0x57, 0xfc, 0xf0, 0x37, 0x00, 0x00, 0xff, 0xff, 0x58, 0xc4, 0x50, 0x04, 0x5d, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GRPCApiClient is the client API for GRPCApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCApiClient interface {
	// Getting all new accounts
	GetNewAccounts(ctx context.Context, in *NewAccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error)
}

type gRPCApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCApiClient(cc grpc.ClientConnInterface) GRPCApiClient {
	return &gRPCApiClient{cc}
}

func (c *gRPCApiClient) GetNewAccounts(ctx context.Context, in *NewAccountsRequest, opts ...grpc.CallOption) (*AccountsResponse, error) {
	out := new(AccountsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.GRPCApi/GetNewAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCApiServer is the server API for GRPCApi service.
type GRPCApiServer interface {
	// Getting all new accounts
	GetNewAccounts(context.Context, *NewAccountsRequest) (*AccountsResponse, error)
}

// UnimplementedGRPCApiServer can be embedded to have forward compatible implementations.
type UnimplementedGRPCApiServer struct {
}

func (*UnimplementedGRPCApiServer) GetNewAccounts(ctx context.Context, req *NewAccountsRequest) (*AccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewAccounts not implemented")
}

func RegisterGRPCApiServer(s *grpc.Server, srv GRPCApiServer) {
	s.RegisterService(&_GRPCApi_serviceDesc, srv)
}

func _GRPCApi_GetNewAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCApiServer).GetNewAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.GRPCApi/GetNewAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCApiServer).GetNewAccounts(ctx, req.(*NewAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.GRPCApi",
	HandlerType: (*GRPCApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNewAccounts",
			Handler:    _GRPCApi_GetNewAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mouselive.proto",
}
